// // import { LightningElement } from 'lwc';

// // export default class HotelRooms extends LightningElement {
// //     hotelRooms=[
// //         {
// //             name:'Taj Hotel',
// //             price:1000,
          
// //         },
// //         {
// //             name:'Leela Palace',
// //             price:2000,
          
// //         },
// //         {
// //             name:'Marriott Hotel',
// //             price:3000,
            
// //         }]
// // }




// import { createElement } from '@lwc/engine-dom';
// import HotelRooms from 'c/hotelRooms';

// describe('c-hotel-rooms', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//     });

//     it('TODO: test case generated by CLI command, please fill in test logic', () => {
//         // Arrange
//         const element = createElement('c-hotel-rooms', {
//             is: HotelRooms
//         });

//         // Act
//         document.body.appendChild(element);

//         // Assert
//         // const div = element.shadowRoot.querySelector('div');
//         expect(1).toBe(1);
//     });
// });




import { LightningElement } from 'lwc';
 
export default class HotelRooms extends LightningElement {
    hotelRoomsInfo;
    selectedHotelRoom;
 
    constructor(){
        super();
        this.selectedHotelRoom = {roomName:'Koshi',roomCapacity:4};
        this.hotelRoomsInfo = [
            {roomName:'A-01',roomCapacity:4},
            {roomName:'A-02',roomCapacity:2},
            {roomName:'A-03',roomCapacity:1},
            {roomName:'B-01',roomCapacity:3},
            {roomName:'B-02',roomCapacity:5},
            {roomName:'C-01',roomCapacity:6},
            {roomName:'C-02',roomCapacity:2}
        ]






        //eventlistener for 'tileclick' event of hotel room component
        this.template.addEventListener('tileclick',(evt)=>this.tileClickHandler(evt));
       
       
      
    }
 
    tileClickHandler(evt){
        console.log('tileClickHandler!');
        console.log(evt.detail);
        this.selectedHotelRoom = evt.detail;
    }
}